// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGubN8XRY3seJuhztg4LT1V7lGybiKzqY',
    appId: '1:71677952912:web:56156e3550692d051ce915',
    messagingSenderId: '71677952912',
    projectId: 'life-link-6472a',
    authDomain: 'life-link-6472a.firebaseapp.com',
    storageBucket: 'life-link-6472a.firebasestorage.app',
    measurementId: 'G-QG3X0P6G8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF9SJN4c8Rq43HGsVJZ_MdcGNfS_ss5ZU',
    appId: '1:71677952912:android:c17b642d612608081ce915',
    messagingSenderId: '71677952912',
    projectId: 'life-link-6472a',
    storageBucket: 'life-link-6472a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZwnQM-gOZ5BkKcWRtbitmX7SS5hsX1E',
    appId: '1:71677952912:ios:f566dbfb2228e5501ce915',
    messagingSenderId: '71677952912',
    projectId: 'life-link-6472a',
    storageBucket: 'life-link-6472a.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZwnQM-gOZ5BkKcWRtbitmX7SS5hsX1E',
    appId: '1:71677952912:ios:f566dbfb2228e5501ce915',
    messagingSenderId: '71677952912',
    projectId: 'life-link-6472a',
    storageBucket: 'life-link-6472a.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGubN8XRY3seJuhztg4LT1V7lGybiKzqY',
    appId: '1:71677952912:web:7d7c7d976e7dbdff1ce915',
    messagingSenderId: '71677952912',
    projectId: 'life-link-6472a',
    authDomain: 'life-link-6472a.firebaseapp.com',
    storageBucket: 'life-link-6472a.firebasestorage.app',
    measurementId: 'G-T41S54VZ4D',
  );
}
